package sample;

import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.File;

import javafx.scene.control.Alert;
import javafx.scene.control.Label;

public class Input
{

    // 1: random array generated automatically
    public static void createInput(int numberOfElements, int maxNumberReached)
    {
        Main.arrayInput= new int[numberOfElements];
        try
        {
            Main.arrayInput=Utilities.createRandomArray(numberOfElements, maxNumberReached);
        }
        catch(Exception ex)
        {
            System.out.println("Eccezzione Generata --> " + ex.getLocalizedMessage());
        }
    }

    // 2: array generated by user input
    public static void createInput(int[] a)
    {
        Main.arrayInput= new int[a.length];
        for(int i=0; i<a.length; i++)
        {
            Main.arrayInput[i]=a[i];
        }
    }


    // 3: array readed by text file
    public static void createInput(File file)
    {
        int i=0; int j=0; int currentNumber=0;
        int cont=-1;
        String line = "";
        try
        {
            FileInputStream fis = new FileInputStream(file);
            FileInputStream fileinputStream = new FileInputStream(file);
            //Construct BufferedReader from InputStreamReader
            BufferedReader br = new BufferedReader(new InputStreamReader(fis));
            BufferedReader buffer = new BufferedReader(new InputStreamReader(fileinputStream));
            // set array dimension
            while (br.readLine()!= null)
            {
                cont++;
            }
            br.close();
            if(cont>Main.ARRAY_LENGHT)
                cont=Main.ARRAY_LENGHT;
            Main.arrayInput= new int[cont];
            line = "";
            Label exception = null;
            while (i<cont)
            {
                try
                {
                    line = buffer.readLine();
                    currentNumber = Integer.parseInt(line);
                    if (currentNumber!=0) {
                        Main.arrayInput[j] = currentNumber;
                        j++;
                    }
                    i++;
                    exception=new Label("Tutto ok");
                }
                catch (NumberFormatException ex)
                {
                    System.out.println("Eccezione generata dalla conversione dei valori nel file di testo --> " + ex.getLocalizedMessage());
                }
                finally
                {
                    if(exception==null)
                    {
                        Alert alert = new Alert(Alert.AlertType.WARNING);
                        alert.setTitle("Attenzione");
                        alert.setHeaderText("Eccezione Generata nella lettura del file di testo in input");
                        alert.setContentText("controllare che ogni riga contenga solo numeri \n riga interessata: " + (i+1));
                        alert.showAndWait();
                        i++;
                    }
                    else
                        exception = null;
                }
            }
            buffer.close();
        }
        catch (FileNotFoundException ex)
        {
            System.out.println("Eccezione generata nella ricerca del file di testo nella directory corrente --> " + ex.getMessage());
        }
        catch (IOException ex) {
            System.out.println("Eccezione generata dalla conversione dei valori nel file di testo --> " + ex.getMessage());
        }
    }

    Input()
    {
        Main.arrayInput=new int[Main.ARRAY_LENGHT];
    }

}
